version: '3'
services:
  mysql:
    image: mariadb
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always
  wordpress:
      image: wordpress:php7.3-fpm-alpine
      volumes:
        - ./data/html:/var/www/html
      depends_on:
        - mysql
      environment:
        WORDPRESS_DB_HOST: mysql
        MYSQL_ROOT_PASSWORD: root
        WORDPRESS_DB_NAME: root
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
        WORDPRESS_TABLE_PREFIX: wp_
      links:
        - mysql
      restart: always
  nginx:
      image: nginx:alpine
      volumes:
        - ./inception/srcs/requirements/nginx/conf:/etc/nginx/conf.d
        - ./data/html:/var/www/html
      ports:
        - 80:80
      links:
        - wordpress
